pipeline {
    agent any     

    stages 
	{ 	

		stage('Build and Unit Test') { 
			steps {	
				
				echo "####################################"
				echo "Running Unit Test"
				echo "####################################"
                sh "python -m unittest discover test/unit/"
				echo "####################################"
               			  							
			}			
		}

		stage('Integration Test') { 
			steps {

				echo "####################################"
				echo "Running Integration Test"
				echo "####################################"
				sh "python -m unittest discover test/integration/"
				echo "####################################"  	
			}

		}
		
		
		stage('Build Imagem Docker DISCOUNT API ') { 
			when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
			steps {			
				echo "####################################"
				echo "Building Docker Image"	
				echo "####################################"
                sh "docker build -t renatoadsumus/api-discount:staging ."				
				echo "####################################"              
						
			}			
		}	        

       stage('Deploy') { 
			
			when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
			steps {		
				sh "docker stop $(docker ps -q)"	
				echo "####################################"
				echo "Gerando a Imagem Docker da Aplicacao"	
				echo "####################################"               	
				 sh "docker run -d -p 8082:5000 renatoadsumus/api-discount:staging"
						
			}						
		}  	
	}	

}