pipeline {
    agent any     

    stages 
	{ 	

		stage('Build and Unit - Integration Test') {
			steps {	
				
				echo "####################################"
				echo "Running Unit Test"
				echo "####################################"
                sh "python -m unittest discover test"
				echo "####################################"
               			  							
			}			
		}
		
		
		stage('Build Image Docker DISCOUNT API ') {
			when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
			steps {			
				echo "####################################"
				echo "Building Docker Image"	
				echo "####################################"
                sh "docker build -t renatoadsumus/api-discount:staging ."				
				echo "####################################"              
						
			}			
		}	        

       stage('Deploy') { 
			
			when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
			steps {		
				//sh "docker stop api_staging"
				echo "####################################"
				echo "Gerando a Imagem Docker da Aplicacao"	
				echo "####################################"               	
				 sh "docker run -d --rm -p 8082:5000 --name api_staging renatoadsumus/api-discount:staging"
						
			}						
		}  	
	}	

}