pipeline {
    agent any     

    stages 
	{ 					
		
		stage('Build Image Docker DISCOUNT API ') {
			when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
			steps {			
				echo "####################################"
				echo "Recovering Last Version Stable"	
				echo "####################################"
                sh "docker build tag renatoadsumus/api-discount:fallback renatoadsumus/api-discount:latest"				
				echo "####################################"              
						
			}			
		}	        

       stage('Deploy') { 
			
			when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
			steps {		
				sh "docker stop api_production"
				echo "####################################"
				echo "Gerando a Imagem Docker da Aplicacao"	
				echo "####################################"               	
				 sh "docker run -d --rm -p 8080:5000 --name api_production renatoadsumus/api-discount:latest"
						
			}						
		}  	
	}

}