pipeline {
    agent any     

    stages 
	{ 	

		stage('Build and Unit - Integration Test') {
			steps {	

				echo "####################################"
				echo "Running Unit Test"
				echo "####################################"
                sh "python -m unittest discover test"
				echo "####################################"  
				
               			  							
			}			
		}

		
		
		stage('Build Image Docker DISCOUNT API ') {
			when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
			steps {			
				echo "####################################"
				echo "Building Docker Image"	
				echo "####################################"
				sh "docker tag renatoadsumus/api-discount:latest renatoadsumus/api-discount:fallback"	
                sh "docker build -t renatoadsumus/api-discount:latest ."							
				echo "####################################"              
						
			}			
		}	        

       stage('Deploy') { 
			
			when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
			steps {			
                //sh "docker stop api_production"
				echo "####################################"
				echo "Running Container API"	
				echo "####################################"               	
				 sh "docker run -d --rm -p 8080:5000 --name api_production renatoadsumus/api-discount:latest"
				echo "####################################"
						
			}						
		}  	
	}
}